### ISSUE TITLE
Append "-readme" to the end of the file names being saved

### ISSUE THREAD

**Issue by BostNisReport** [wgoldm/plugin-notes-fork#4]
Currently, this plugin fork should be saving into the `/plugins/` root directory so they can display alongside the plugins they represent.

The filename is `{plugin-slug}.md`

Can you update this to be saved-as and read back in as: `{plugin-slug}-readme.md` please.

**Comment by tmonzur** [comment]
Updated

**Comment by tmonzur** [comment]
Yes already set this status inside the code. and on the plugin root the file will need to be available. As client told that he already kept the file with that name. I also prepare the code in a way that the color drop-down list come from that page. And also in previous update mentioned that "\n" will require to the end of each line. here is the sample format of the file.
[plugin-notes-fork-readme.zip](https://github.com/wgoldm/plugin-notes-fork/files/2023604/plugin-notes-fork-readme.zip)
