### ISSUE TITLE
Update the template text to be pulled from this file in the `plugins` root

### ISSUE THREAD

**Issue by BostNisReport** [wgoldm/plugin-notes-fork#5]
I have placed this file in the root of dev.waves: 77.104.177.66/applications/ffqssbbnph/public_html/wp-content/plugins/

This plugin has a function to use a notes template - I assume saved to and pulled from the Options table.

When this file is present - can you make it so that the template is pulled fro and saved back to this file instead please?

**Comment by tmonzur** [comment]
Not clear the comments...

**Comment by BostNisReport** [comment]
I had removed the file during a cleanup, have returned it there now, it is the same file as attached on skype so you can also copy it to /plugins/ o your localhost to work with

plugin-slug-readme.md was created incorrectly by the previous developer - difficulties communicating with him.

**Comment by tmonzur** [comment]
in plugin list we have add and edit notes feature. When we click on add/edit it display 2 things..

1. Dropdown of status with color code. [Right now the dropdown come from file. I have uploaded a file "plugin-notes-fork-readme.md" here, inside that keep the format of the list. You must need to use '\n' end of each line to make proper dropdown.]

2. Multi line text input. 

You mean to prepare this template from the file plugin-slug-readme.md ???

Also you mentioned to save data? Currently data saved to database table. where you want to save data? 

Please clear.

**Comment by BostNisReport** [comment]
I have no idea what that is because the last developer was next to useless for communications - that is nothing to do with anything I asked for I am afraid.

**Comment by tmonzur** [comment]
Yes the template dropdown now come from the file plugin-notes-fork-readme.md

and its format as attachment.
[plugin-notes-fork-readme.zip](https://github.com/wgoldm/plugin-notes-fork/files/2023609/plugin-notes-fork-readme.zip)
