### ISSUE TITLE
Don't use `plugin-slug-readme.md--`

### ISSUE THREAD

**Issue by BostNisReport** [wgoldm/plugin-notes-fork#7]
Needs Testing (purple #E9E2F8)
Testing in Progress (orange #F9E8E6)
Needs Debugging (red #F9E6F4)
Needs Development (yellow #F9F0E6)
Needs Configuration (yellow-green #F9F7E6)
Development-Only (Grey #D7DADD)
Satisfactory As Supplied (light-green #F0F8E2)
Development Complete (green #EBF9E6)
Documentation Requested (light-blue #EAF2FA)
Developer Review Requested (dark-blue #E6F9F9)

**Comment by tmonzur** [comment]
ok

**Comment by BostNisReport** [comment]
Can you remove that, and change the plugin to use this file & contents instead, when the same file is NOT in the /plugins/ root:

_plugin-notes-slug-readme-template.md

Otherwise if the file is already present in /plugins/ root, it should read and write the template to that file please.

The reason for this, is the source and maintenance of these files is going to be from this repo:


https://gitlab.com/agentdesign/wordpress/wordpress-plugins-documentation/tree/develop


when the directory becomes read-only to FTP users and updatable only via Git.

**Comment by tmonzur** [comment]
yes the system not reading that file..
